version: '3.8'
services:
  keycloak:
    image: jboss/keycloak:16.1.1
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak:/opt/jboss/keycloak/imports
#    command:
#      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
  app:
    build: .
    ports:
      - "8081:8081"
