version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dbinit:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      booknet:
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    ports:
      - "8082:8080"
    networks:
      booknet:
  keycloak:
    container_name: keycloak
    image: bitnami/keycloak
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak:/realm
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: db
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keypasswd
      KEYCLOAK_EXTRA_ARGS: "-Dkeycloak.import=/realm/realm-export.json"
    networks:
      booknet:
        aliases:
          - keycloak.bookstore.net
    depends_on:
      - db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      keycloak.auth-server-url: http://keycloak.bookstore.net:8080
      spring.datasource.url: jdbc:postgresql://db:5432/bookstore
      spring.datasource.username: bookstore
      spring.datasource.password: bookpasswd
    networks:
      booknet:
    depends_on:
      - db
networks:
  booknet:
volumes:
  postgres_data:
    driver: local