export const FETCH_BOOKS = 'FETCH_BOOKS';
export const FETCH_BOOKS_START = 'FETCH_BOOKS_START';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAIL = 'FETCH_BOOKS_FAIL';

export const FETCH_BOOK = 'FETCH_BOOK';
export const FETCH_BOOK_START = 'FETCH_BOOK_START';
export const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS';
export const FETCH_BOOK_FAIL = 'FETCH_BOOK_FAIL';

export const SAVE_BOOK = 'SAVE_BOOK';
export const SAVE_BOOK_START = 'SAVE_BOOK_START';
export const SAVE_BOOK_SUCCESS = 'SAVE_BOOK_SUCCESS';
export const SAVE_BOOK_FAIL = 'SAVE_BOOK_FAIL';

export const DELETE_BOOK = 'DELETE_BOOK';
export const DELETE_BOOK_START = 'DELETE_BOOK_START';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAIL = 'DELETE_BOOK_FAIL';

export const TOGGLE_WISH = 'TOGGLE_WISH';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';

export const KEYCLOAK_EVENT = 'KEYCLOAK_EVENT';
export const USERNAME_CHANGED = 'USERNAME_CHANGED';
export const TOKEN_CHANGED = 'TOKEN_CHANGED';

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';